config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :races
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :race_comments, only: [:create, :destroy]
  resources :races, only: [:edit,:update,:show, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@micropost = current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page],  per_page: 10)
      @race_feed_items = current_user.race_feed
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_default.html.erb
<div class="center ">
  <%= image_tag'logo_large.png', id: "splash-logo"%>

  <h2>
    your race tracker and racer network
  </h2>
  <h3>racelockr is a race-tracking service where users can sign up, store their race results / photos / discussions, and share and network with others.</h3>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <p>
  	<h2>or <%= link_to "Sign in", signin_path %></h2>
  </p>
</div>

app/views/static_pages/_home_signedin.html.erb
<div class="row">
	<aside class="col-md-3 col-sm-4">
		<div class="row">
			<section class="col-sm-12">
				<%= render 'shared/user_info', user: current_user %>
			</section>
			<section class="col-sm-12">
				<%= render 'shared/stats' %>
			</section>
			<section class="col-sm-12">
				<a class="btn btn-large btn-primary" href="<%= new_race_path %>">Add a Race</a>
			</section>
			<section class="col-sm-12">
				<%= render 'shared/micropost_form' %>
			</section>
		</div>
	</aside>
	<div class="col-md-9 col-sm-8">
		<h3>Races Feed</h3>
		<%= render 'shared/race_feed' %>
<!-- 	</div>
	<div class="col-sm-8"> -->
		<h3>Micropost Feed </h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	The concept will be a race-tracking service where users can sign up, store their race results / photos / discussions, and share and network with others.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  You can contact us by shooting an email to <a href="mailto:dlogsr@gmail.com">dlogsr@gmail.com</a>!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
	Coming soon!
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<%= render 'static_pages/home_signedin' %>
<% else %>
	<%= render 'static_pages/home_default' %>
<% end %>