config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :races
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :race_comments, only: [:create, :destroy]
  resources :races, only: [:edit,:update,:show, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/shared/_delete.html.erb
<%= link_to "delete", object, method: :delete,
								 data: {confirm: "Ya sure?"}%>

app/views/shared/_edit_delete_race.html.erb
<%= link_to "edit race", edit_race_path(object) %>
 | <%= render 'shared/delete', object:object %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts list-group">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>" class="list-group-item">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
		<%= render 'shared/delete', object: feed_item %>
	<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new post..." %>
	</div>
	<div class="charCountBox span2" style="display:none">
		<b id="charCount">140</b> characters left.
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_race_feed.html.erb
<% if @race_feed_items.any? %>
	<ol class="list-group">
		<%= render partial: 'shared/race_feed_item', collection: @race_feed_items.limit(5) %>
	</ol>
	<!-- <%= will_paginate @feed_items %> -->
<% end %>

app/views/shared/_race_feed_item.html.erb
<li id="<%= race_feed_item.id %>" class="list-group-item">
	<div class="row">
		<div class="col-xs-3 text-center center-block col-md-1">
			<%= link_to gravatar_for(race_feed_item.user), race_feed_item.user %>
		</div>
		<div class="col-xs-9 col-md-11">
			<span class="user race-feed-span">
				<%= link_to race_feed_item.user.name, race_feed_item.user %>
			</span>
			<span class="content race-feed-span">
				ran the 
				<%= link_to(race_feed_item) do %>
					<%= race_feed_item.name %> 
				<% end %>
				on <%= race_feed_item.date%></span>
			<span class="description race-feed-span">
				<%= race_feed_item.description %>
			</span>
			<span class="comments race-feed-span">
				<% if race_feed_item.race_comments.count != 0%>
					<%= pluralize(race_feed_item.race_comments.count, "comment") %>
				<% end %>
			</span>
		</div>
	</div>
</li>

app/views/shared/_race_list.html.erb
<% if @user.races.any? %>
	<ol class="microposts list-group">
		<%= render @races %>
	</ol>
	<%= will_paginate @races, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="row">
	<section class="col-sm-12">
		<%= render 'shared/user_info', user: @user %>
	</section>
	<section class="col-sm-12">
		<%= render 'shared/stats' %>
	</section>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="col-sm-12">
	<div class="row stats">
		<div class="col-xs-4">
			<a href="<%= following_user_path(@user) %>">
				<strong id="following" class="stat">
					<%= @user.followed_users.count %>
				</strong>
				following
			</a>
		</div>
		<div class="col-xs-4">
			<a href="<%=followers_user_path(@user) %>">
				<strong id="followers" class="stat">
					<%= @user.followers.count %>
				</strong>
				followers
			</a>
		</div>
		<div class="col-xs-4">
			<a href="<%=races_user_path(@user) %>">
				<strong id="races" class="stat">
					<%= @user.races.count %>
				</strong>
				races
			</a>
		</div>
	</div>
</div>

app/views/shared/_user_info.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="row center-block">
			<%= link_to gravatar_for(user, size:100), user, class: "col-xs-12 col-sm-7 sidebar center user-image"%>
			<h1 class="col-xs-12 col-sm-5 center">
				<%= link_to user.name, user %>
			</h1>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<h2>
			<%= user.email %>
			<br />
			<%= user.location %>
		</h2>
	</div>
</div>