config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :races
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :race_comments, only: [:create, :destroy]
  resources :races, only: [:edit,:update,:show, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    (c)2014 racelockr
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainnav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo_small_white_2x.png", id:"logo-img"), root_path, id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="mainnav-collapse">
      <ul class="nav navbar-right navbar-nav list-inline">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Profile", current_user %></li>
              <li><%= link_to "Your Races", races_user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <link href="http://fonts.googleapis.com/css?family=Raleway:300" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
    	<% flash.each do |key, value| %>
    		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
    	<% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>